"""
PDF Report Generator for SpectreScan
by BitSpectreLabs
"""

from typing import List, Dict, Optional, TYPE_CHECKING
from pathlib import Path
from datetime import datetime
from spectrescan.core.utils import ScanResult, HostInfo

if TYPE_CHECKING:
    from reportlab.graphics.shapes import Drawing

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, 
        Spacer, PageBreak, Image, KeepTogether
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.graphics.shapes import Drawing
    from reportlab.graphics.charts.piecharts import Pie
    from reportlab.graphics.charts.barcharts import VerticalBarChart
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_pdf_report(
    results: List[ScanResult],
    output_path: Path,
    summary: Optional[Dict] = None,
    host_info: Optional[Dict[str, HostInfo]] = None,
    include_charts: bool = True
) -> None:
    """
    Generate professional PDF report with charts.
    
    Args:
        results: List of scan results
        output_path: Output PDF file path
        summary: Optional scan summary statistics
        host_info: Optional host information dictionary
        include_charts: Whether to include charts (default: True)
        
    Raises:
        ImportError: If reportlab is not installed
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError(
            "ReportLab is required for PDF generation. "
            "Install it with: pip install reportlab"
        )
    
    # Create PDF document
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=1*inch,
        bottomMargin=0.75*inch
    )
    
    # Build story (content elements)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#6B46C1'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#6B46C1'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    story.append(Paragraph("SpectreScan Security Report", title_style))
    story.append(Paragraph(
        f"Generated by BitSpectreLabs",
        styles['Normal']
    ))
    story.append(Paragraph(
        f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles['Normal']
    ))
    story.append(Spacer(1, 0.3*inch))
    
    # Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    
    if summary:
        summary_data = [
            ["Metric", "Value"],
            ["Total Targets Scanned", str(summary.get('total_targets', 'N/A'))],
            ["Total Ports Scanned", str(summary.get('total_scanned', 0))],
            ["Open Ports Found", str(summary.get('open_count', 0))],
            ["Closed Ports", str(summary.get('closed_count', 0))],
            ["Filtered Ports", str(summary.get('filtered_count', 0))],
            ["Scan Duration", f"{summary.get('scan_time', 0):.2f} seconds"],
            ["Scan Type", summary.get('scan_type', 'N/A')],
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 3*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6B46C1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))
    
    # Charts
    if include_charts and summary:
        story.append(Paragraph("Port Status Distribution", heading_style))
        
        # Pie chart for port states
        open_count = summary.get('open_count', 0)
        closed_count = summary.get('closed_count', 0)
        filtered_count = summary.get('filtered_count', 0)
        
        if open_count + closed_count + filtered_count > 0:
            pie_chart = _create_pie_chart(open_count, closed_count, filtered_count)
            story.append(pie_chart)
            story.append(Spacer(1, 0.3*inch))
    
    # Host Information
    if host_info:
        story.append(Paragraph("Host Information", heading_style))
        
        for ip, info in host_info.items():
            host_data = [
                ["Property", "Value"],
                ["IP Address", info.ip],
                ["Hostname", info.hostname or "N/A"],
                ["Operating System", info.os_guess or "Unknown"],
                ["TTL", str(info.ttl) if info.ttl else "N/A"],
                ["Latency", f"{info.latency_ms:.2f} ms" if info.latency_ms else "N/A"],
                ["Status", "Up" if info.is_up else "Down"],
            ]
            
            host_table = Table(host_data, colWidths=[2*inch, 4*inch])
            host_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6B46C1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
            ]))
            
            story.append(host_table)
            story.append(Spacer(1, 0.2*inch))
    
    # Detailed Results
    story.append(PageBreak())
    story.append(Paragraph("Detailed Scan Results", heading_style))
    
    # Group results by host
    results_by_host = {}
    for result in results:
        if result.host not in results_by_host:
            results_by_host[result.host] = []
        results_by_host[result.host].append(result)
    
    for host, host_results in results_by_host.items():
        story.append(Paragraph(f"Target: {host}", styles['Heading3']))
        
        # Filter open ports for detailed listing
        open_ports = [r for r in host_results if r.state == 'open']
        
        if open_ports:
            table_data = [["Port", "Protocol", "State", "Service", "Banner"]]
            
            for result in open_ports:
                banner_preview = result.banner[:40] + "..." if result.banner and len(result.banner) > 40 else (result.banner or "")
                table_data.append([
                    str(result.port),
                    result.protocol,
                    result.state,
                    result.service or "unknown",
                    banner_preview
                ])
            
            results_table = Table(table_data, colWidths=[0.7*inch, 0.9*inch, 0.8*inch, 1.5*inch, 2.6*inch])
            results_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6B46C1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ]))
            
            story.append(results_table)
        else:
            story.append(Paragraph("No open ports found.", styles['Normal']))
        
        story.append(Spacer(1, 0.2*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(
        "This report was generated by SpectreScan - Professional Network Security Tools",
        styles['Normal']
    ))
    story.append(Paragraph(
        "© 2025 BitSpectreLabs. All rights reserved.",
        styles['Normal']
    ))
    
    # Build PDF
    doc.build(story)


def _create_pie_chart(open_count: int, closed_count: int, filtered_count: int) -> "Drawing":
    """
    Create a pie chart for port status distribution.
    
    Args:
        open_count: Number of open ports
        closed_count: Number of closed ports
        filtered_count: Number of filtered ports
        
    Returns:
        Drawing object containing the pie chart
    """
    drawing = Drawing(400, 200)
    
    pie = Pie()
    pie.x = 150
    pie.y = 50
    pie.width = 100
    pie.height = 100
    
    pie.data = [open_count, closed_count, filtered_count]
    pie.labels = [
        f'Open ({open_count})',
        f'Closed ({closed_count})',
        f'Filtered ({filtered_count})'
    ]
    pie.slices.strokeWidth = 0.5
    pie.slices[0].fillColor = colors.HexColor('#10B981')  # Green
    pie.slices[1].fillColor = colors.HexColor('#EF4444')  # Red
    pie.slices[2].fillColor = colors.HexColor('#F59E0B')  # Yellow
    
    drawing.add(pie)
    
    return drawing
